version: 1
builder:
  configs:
    - documentation_targets: [_DNSSupport, _PreferenceSupport, _PrivilegeSupport, _ProfileSupport, Dashboard, Netbot, NetbotDaemons, NetbotKit, NetbotLite, NetbotLiteData]
