// ===----------------------------------------------------------------------=== //
//
// This source file is part of the Netbot open source project
//
// Copyright © 2026 Junfeng Zhang and the Netbot project authors
// Licensed under Apache License v2.0
//
// See https://www.apache.org/licenses/LICENSE-2.0 for license information
//
// SPDX-License-Identifier: Apache-2.0
//
// ===----------------------------------------------------------------------=== //

#if canImport(Darwin) || swift(>=6.3)
  import Observation
#endif

#if canImport(FoundationEssentials)
  import FoundationEssentials
#else
  import Foundation
#endif

#if canImport(SwiftData) && SWTNE_REQUIRES_SQL
  import SwiftData
#else
  import NetbotSQL
#endif

@available(SwiftStdlib 6.0, *)
extension V1 {

  /// Information about an application and its associated activity.
  ///
  /// Program stores metadata describing an application, including its
  /// name, bundle location, executable, icon, and aggregated reporting data.
  ///
  /// Use this type to associate network activity and data transfer metrics
  /// with a specific application.
  @Model public class Program {

    #Unique<Program>([\Program.localizedName])

    /// The localized display name of the application.
    ///
    /// This value is intended for presentation to users and may vary
    /// depending on the current locale.
    @Attribute(.unique)
    public var localizedName: String = ""

    /// The URL of the application's bundle.
    ///
    /// This value identifies the bundle package that contains the
    /// application's resources and executable.
    public var bundleURL: URL?

    /// The URL of the application's executable.
    ///
    /// This value identifies the executable file launched by the system.
    public var executableURL: URL?

    /// The application's icon in TIFF format.
    ///
    /// This value contains the raw TIFF representation of the application's
    /// icon and may be used to recreate an image for display purposes.
    @Attribute(.externalStorage)
    public var iconTIFFRepresentation: Data?

    /// Reports associated with processes belonging to the application.
    ///
    /// Each report describes activity observed for an individual process.
    @Relationship(inverse: \V1.ProcessReport.program)
    public var processReports: [V1.ProcessReport] = []

    /// Aggregated data transfer metrics for the application.
    ///
    /// This value summarizes network traffic generated by the application
    /// across its associated processes.
    @Relationship(inverse: \V1.DataTransferReport.program)
    public var dataTransferReport: DataTransferReport?

    /// Creates an empty ``V1/Program`` record.
    public init() {}
  }
}

#if !(canImport(SwiftData) && SWTNE_REQUIRES_SQL)
  @available(SwiftStdlib 6.0, *)
  extension V1.Program: Identifiable {
    public var id: String { persistentModelID }

    public var persistentModelID: String { localizedName }
  }
#endif

@available(SwiftStdlib 6.0, *)
extension V1.Program {

  /// Converts a runtime ``Program`` into a persistent ``V1/Program`` snapshot.
  ///
  /// This method captures the current state of the program at a point in time.
  /// Runtime-only fields (timers, live state transitions, observation locks)
  /// are flattened into persistable values.
  ///
  /// - Parameter data: New `Program` to map.
  public func mergeValues(_ data: NetbotLiteData.Program) {
    #if canImport(SwiftData) && SWTNE_REQUIRES_SQL
      if localizedName != data.localizedName {
        localizedName = data.localizedName
      }
      if bundleURL != data.bundleURL {
        bundleURL = data.bundleURL
      }
      if executableURL != data.executableURL {
        executableURL = data.executableURL
      }
      if iconTIFFRepresentation != data.iconTIFFRepresentation {
        iconTIFFRepresentation = data.iconTIFFRepresentation
      }
    #else
      localizedName = data.localizedName
      bundleURL = data.bundleURL
      executableURL = data.executableURL
      iconTIFFRepresentation = data.iconTIFFRepresentation
    #endif
  }
}
