name: Main

on:
  push:
    branches: [main]

jobs:
  unit-tests:
    name: Unit tests
    uses: hdtls/swift-ci/.github/workflows/unit_tests.yml@main
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN  }}
    with:
      linux_6_1_enabled: true
      linux_6_2_enabled: true
      linux_6_3_enabled: true
      linux_nightly_release_enabled: true
      linux_nightly_main_enabled: true

      macos_6_2_enabled: true
      macos_6_3_enabled: true
